export const userTypes={
    ADD_USER:"ADD_USER",
    UPDATE_USER:"UPDATE_USER",
    DELETE_USER:"DELETE_USER",
    CHANGE_LOADING:"CHANGE_LOADING",
    GET_USERS:"GET_USERS",
    SELECT_USER:"SELECT_USER",
    CHANGE_PAGE:"CHANGE_PAGE",
    SORT_USERS:"SORT_USERS",
    SORT:"SORT",
    FILTER_USERS:"FILTER_USERS"
}